### ISSUE TITLE
Duplicate identifier

### ISSUE THREAD

**Issue by Mauricio-Arantes** [wuzi/ragemp-boilerplate#3]
I received an error saying TS6200: Definitions of the following identifiers conflict with those in another file between types-ragemp-c#master and types-ragemp-s#master

**Comment by wuzi** [comment]
Can you share the typescript and nodejs versions?
Did you change any tsconfig.json?
Did you run `npm run build`? If not, try with `npm run build`.

**Comment by Mauricio-Arantes** [comment]
Versions:
 -3.5.3 TS
 -12.7.1 Node

Yes, in client side i have to make some changes to try apply the NativeUi GIU

I already try use build, but when try build the ragemp-c with ragemp-s, a lot interface error happen.

Maybe we can talk in the Discord? I am in the Rage Discord with the same nickname

**Comment by wuzi** [comment]
> I already try use build, but when try build the ragemp-c with ragemp-s, a lot interface error happen.

You shouldn't build them together, can you share both tsconfig.json?

**Comment by Mauricio-Arantes** [comment]
client config
![image](https://user-images.githubusercontent.com/48027024/80973299-91275780-8df5-11ea-83d7-46087c04bee5.png)

Server config
![image](https://user-images.githubusercontent.com/48027024/80973337-9c7a8300-8df5-11ea-8e99-3848d2581a6d.png)

**Comment by wuzi** [comment]
I see you removed the `types` from client config, so it results in using all the types together, but ragemp-s and ragemp-c have a lot of duplicated stuff. You should remove ragemp-s from client typings.

**Comment by Mauricio-Arantes** [comment]
Tks!
